server:
  port: 8082

spring:
  application:
    name: diet
  config:
    import: optional:configserver:http://localhost:9021/
  datasource:
    url: jdbc:postgresql://localhost:5434/diet-db
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    drive-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_ISSUER_URI:http://localhost:7080/realms/MealTrackingApp}
          jwk-set-uri: ${RESOURCE_SERVER_JWK_SET_URI:http://localhost:7080/realms/MealTrackingApp/protocol/openid-connect/certs}
  cloud:
    function:
      definition: productCreated; productUpdated; productDeleted
    stream:
      bindings:
        productCreated-in-0:
          destination: product.created
          group: ${spring.application.name}
        productUpdated-in-0:
          destination: product.updated
        productDeleted-in-0:
          destination: product.deleted
        productAddedToMeal-out-0:
          destination: product.added.to.meal
        productRemovedFromMeal-out-0:
          destination: product.removed.from.meal
        productUpdatedInMeal-out-0:
          destination: product.updated.in.meal

rabbit:
  host: localhost
  port: 5672
  username: guest
  password: guest
  connection-timeout: 10s

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "Diet MS"
    description: "Microservice for Diets in Meal Tracking Application"
    version: 1.0.0

logging:
  level:
    io:
      github:
        patrykkukula:
          diet-ms: TRACE
    org:
      springframework:
        security: TRACE
  pattern:
    console: "%d{HH:mm:ss} [correlation-id:%X{correlation-id}] %-5level %logger - %msg%n"